sonar.projectKey=SDP_Pipeline_Project
sonar.projectName=SDP Pipeline Project
sonar.organization=your-organization-key
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.exclusions=tests/**,**/README*.md,**/*.yml,**/*.yaml,.bundle/**,sonarqube/**
