sonar.projectKey=SDP_Pipeline_Project
sonar.projectName=SDP_Pipeline_Project
sonar.organization=datawarlock1
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.exclusions=tests/**,**/README*.md,**/*.yml,**/*.yaml,.bundle/**,sonarqube/**,03_Pipeline_Monitoring_AutoRecovery.py
